name: tessl
base: core24
version: '0.27.0'
summary: Tessl keeps coding agents on rails using spec-driven development
description: |
  Install usage docs for your favorite open source library from the Tessl Spec Registry.
  Use the Tessl framework to create your own spec-driven project.

grade: stable
confinement: strict

parts:
  tessl:
    plugin: npm
    npm-include-node: true
    source: https://registry.npmjs.org/@tessl/cli/-/cli-$CRAFT_PROJECT_VERSION.tgz
    source-checksum: sha1/cda5c2c3b1a2d8840978b0ff0374521e47e59080
    npm-node-version: "22"

apps:
  tessl:
    command: tessl
    plugs:
      - home
      - network
