name: tessl
base: core24
version: '0.55.1'
summary: Tessl keeps coding agents on rails using spec-driven development
description: |
  Install usage docs for your favorite open source library from the Tessl Spec Registry
  Create your own internal docs and share with your team
website: https://tessl.io
title: Tessl
license: Proprietary
contact: https://discord.com/invite/jbb2vHnHZQ

grade: stable
confinement: strict

platforms:
  amd64:
  arm64:

parts:
  tessl:
    plugin: npm
    npm-include-node: true
    source: https://registry.npmjs.org/@tessl/cli/-/cli-$CRAFT_PROJECT_VERSION.tgz
    npm-node-version: "22"

apps:
  tessl:
    command: bin/tessl
    plugs:
      - home
      - network
      - removable-media
