name: tessl
base: core24
version: '0.83.0'
summary: Agent Enablement Platform that gives your agents the context they're missing.
description: |
  Install usage docs for your favorite open source library from the Tessl Spec Registry
  Create your own internal docs and share with your team
website: https://tessl.io
issues: https://github.com/tesslio/cli/issues
title: Tessl
license: Proprietary
contact: https://discord.com/invite/jbb2vHnHZQ

grade: stable
confinement: classic

platforms:
  amd64:
  arm64:

parts:
  tessl:
    plugin: nil
    source:
      - on amd64: https://install.tessl.io/binaries/$CRAFT_PROJECT_VERSION/tessl-$CRAFT_PROJECT_VERSION-linux-x64.tar.gz
      - on arm64: https://install.tessl.io/binaries/$CRAFT_PROJECT_VERSION/tessl-$CRAFT_PROJECT_VERSION-linux-arm64.tar.gz
    override-build: |
      install -D -m 0755 tessl-$CRAFT_PROJECT_VERSION-linux-* $CRAFT_PART_INSTALL/bin/tessl

apps:
  tessl:
    command: bin/tessl
    environment:
      TESSL_MANAGED_BY_NPM: "0"
      TESSL_AUTO_UPDATE_INTERVAL_MINUTES: "0"
